DROP DATABASE IF EXISTS postal;
CREATE DATABASE postal;
USE postal;
CREATE TABLE pcode (
    id INT AUTO_INCREMENT PRIMARY KEY,
    postcode CHAR(4) NOT NULL,
    locality CHAR(40) NOT NULL,
    state CHAR(3) NOT NULL
);
