DROP DATABASE postal;
CREATE DATABASE postal;
USE postal;
CREATE TABLE pcode (
    id INT(4) AUTO_INCREMENT PRIMARY KEY,
    postcode VARCHAR(4) NOT NULL,
    locality VARCHAR(40) NOT NULL,
    state VARCHAR(3) NOT NULL
);
